package br.com.ouviacess.view;

import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import br.com.ouviacess.dto.RequerimentosDTO;
import br.com.ouviacess.ctr.RequerimentosCTR;

/**
 *
 * @author claud
 */
public class ExibirImagemVIEW extends javax.swing.JFrame {

    RequerimentosDTO requerimentosDTO = new RequerimentosDTO(); //Cria um objeto requerimentosDTO
    RequerimentosCTR requerimentosCTR = new RequerimentosCTR(); //Cria um objeto requerimentosrCTR
    
    private int id_requerimento;

    /**
     * Creates new form Teste
     */
    public ExibirImagemVIEW(int id_requerimento) {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//      Centralizar o JFrame na tela
        setLocationRelativeTo(null);
        // Impedir que a janela seja maximizada
        //setResizable(false);
        
        this.id_requerimento = id_requerimento;
        mostraFoto();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        LabelImagem = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1270, 720));
        setSize(new java.awt.Dimension(1270, 720));

        LabelImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome.setText("teste");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void mostraFoto(){
       try {
            LabelImagem.setText("");

            requerimentosDTO.setId_requerimento(this.id_requerimento);
            ResultSet rs = requerimentosCTR.consultarImagem(requerimentosDTO, 1);
            if (rs.next()) {
                nome.setText(rs.getString("nome"));
                ManipularImagemVIEW.exibiImagemLabel(rs.getBytes("dados_arquivo"), LabelImagem);
            } else {
                JOptionPane.showMessageDialog(null, "Imagemagem não encontrada!!!");
                nome.setText("");
                LabelImagem.setText("");
                LabelImagem.setIcon(new ImageIcon(""));
            }

        } catch (Exception ex) {
            System.out.println("Erro: " + ex.getMessage());
        } finally {
            requerimentosCTR.CloseDB();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImagem;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
