/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ouviacess.view;

import javax.swing.JFrame;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author Aluno
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalVIEW() {
      initComponents();
      this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ImageIcon imageicon = new ImageIcon(getClass().getResource("imagens/FundoPrincipal.png"));
        Image image = imageicon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics graphics){
                graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        menuBar = new javax.swing.JMenuBar();
        menuRequerimentos = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuRequerimentos.setText("Requerimentos");
        menuRequerimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRequerimentosMouseClicked(evt);
            }
        });
        menuRequerimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRequerimentosActionPerformed(evt);
            }
        });
        menuBar.add(menuRequerimentos);

        menuUsuarios.setText("Usuários");
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuariosMouseClicked(evt);
            }
        });
        menuBar.add(menuUsuarios);

        jMenu1.setText("Perfil");
        menuBar.add(jMenu1);

        menuSair.setBackground(new java.awt.Color(255, 51, 51));
        menuSair.setMnemonic('h');
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // MENU DA PRINCIPAL - NAVBAR
    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuRequerimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRequerimentosActionPerformed
        
    }//GEN-LAST:event_menuRequerimentosActionPerformed

    private void menuRequerimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRequerimentosMouseClicked
        RequerimentosVIEW requerimentosVIEW = new RequerimentosVIEW();
         this.desktopPane.add(requerimentosVIEW);
         requerimentosVIEW.setVisible(true);
         requerimentosVIEW.setPosicao();
    }//GEN-LAST:event_menuRequerimentosMouseClicked

    private void menuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseClicked
        UsuariosVIEW usuariosVIEW = new UsuariosVIEW();
         this.desktopPane.add(usuariosVIEW);
         usuariosVIEW.setVisible(true);
         usuariosVIEW.setPosicao();
    }//GEN-LAST:event_menuUsuariosMouseClicked
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuRequerimentos;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables

}
